import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html
            className="w-full h-full min-h-screen max-h-[1024px] bg-stone-100 text-stone-900 dark:bg-stone-800 dark:text-stone-50 overflow-x-hidden antialiased"
            lang="en"
        >
            <body className={`w-full h-full ${inter.className}`}>
                <main className="w-full h-full max-w-5xl mx-auto">
                    {children}
                </main>
            </body>
        </html>
    );
}
